services:
  app:
    build: .

    develop:
      watch:
        - action: sync
          path: src/config
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path: ./uv.lock
